services:
  sonarqube:
    image: sonarqube:10.3-community
    hostname: sonarqube
    container_name: sonarqube
#    read_only: true
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
#      SONAR_JDBC_USERNAME: sonar
#      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
#      - "8000:8000"
    volumes:
      - ./volumes/plugins:/opt/sonarqube/extensions/plugins
#      - ./extensions:/opt/sonarqube/lib/extensions
      - ./volumes/conf:/opt/sonarqube/conf

#  db:
#    image: postgres:15
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    hostname: postgresql
#    container_name: postgresql
#    environment:
#      POSTGRES_USER: sonar
#      POSTGRES_PASSWORD: sonar
#      POSTGRES_DB: sonar